---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks:
  - name: i want install webserver on only ansible ubuntu nodes
    apt: 
      name: "{{mywebpackforubntu}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to start webserver on only ansible node
    service:
      name: "{{mywebpackforubntu}}"
      state: started
    when: ansible_os_family=="Debian"

  - name: i want to install webserver on   only RedHat nodes
    yum:
      name: "{{mywebpackforredhat}}"
      state: present
    when: ansible_os_family=="RedHat"  

  - name: i want to start webserver on only RedHat nodes
    service:
        name: "{{mywebpackforredhat}}"
        state: started
    when: ansible_os_family=="RedHat"
